# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be4269bb110152458acf0e998ad2286d84c1a394d1d79676fd3626a0f7bb595b5d2a95134999912255b34acfac2c30024f18030203a8e0ada851faeb369505f

test:
  secret_key_base: 7fb9e4cefcf6a3f2ab1da54fc602058491ce03a2458d107e2bf52de745a6dacdb5f0b436cf40b8238ca0a064a91628415ba5912a4ca282755f2d38925ffde6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
